version: '3'
services:
  nginx:
    container_name: "nginx"
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on: 
      - rasa
      - action_server
      - mongo
  rasa:
    container_name: "rasa_server"
    build: 
      context: backend
    ports: 
      - 5005:5005
    depends_on:
      - action_server
  action_server:
    container_name: "action_server"
    build: 
      context: actions
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    depends_on:
      - mongo
  mongo:
    image: mongo
  mongo_express:  # this service is a MongoDB UI, and is optional
    image: mongo-express
    container_name: "mongo_express"
    ports:
      - 8081:8081
    links:
      - mongo