version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.10.11-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
		container_name: "action_server"
		build: 
			context: actions
		volumes:
        - ./actions:/app/actions
		ports: 
			- 5055:5055
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasa
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:  # this service is a MongoDB UI, and is optional
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
